<p>
    Tibrus has been making music since 2003, when it was formed to fulfill a final project in a high school music class. Their latest album, Mixed Fuel, was largely recorded in 2005, although some of the music was written in 2003. It wasn't finished until 2009 due to a hiatus to attend college, during which time an excessive amount of partying prevented the completion of the album. Since graduation, there has been a renewed effort by the two of us to get back to what we love most&mdash;making great music.
</p>
<br/>
<p>
	Tibrus is:<br/>
	David 'Wolfgang' Wedemeyer: Guitars, Bass<br/>
	David Coffey: Drums, Keyboards, Vocals (except where noted)<br/>
	Music by Tibrus<br/>
	Mixed Fuel was produced, recorded, mixed, and mastered by Tibrus<br/>
	<br/>
	Very special thanks to the Wedemeyer family for letting us bang really loud drums in your basement all summer. Thanks to Wolfgang and Cassie for doing some ass kicking to get this thing finished. Additional thanks to Lily for inspiring a song deserving of German aggression, and to Dero Goi of <a class="outgoing" href="http://www.oomph.de">OOMPH!</a> and Chris Grantham for German editing assistance.<br/>
</p>
