<?php
    $songs = array(
		'mixed_fuel' => 'Mixed Fuel',
	    'burn' => 'Burn',
	    'driving' => 'Driving',
	    'politics_666' => 'Politics 666',
	    'love_me_computer' => 'Love Me Computer',
	    'i_died_for_you_twice' => 'I Died for You Twice',
	    'im_not_over_you' => "I'm Not Over You",
	    'fusion_locomotion' => 'Fusion Locomotion',
	    'fraga' => 'Fr&aring;ga (radio edit)',
	    'soad_blows' => 'SOAD Blows',
	    'nur_im_traum' => 'Nur Im Traum',
	    'not_dead_yet' => 'Not Dead Yet',
	    'take_me_away' => 'Take Me Away',
	    'fake_people' => 'Fake People');
?>