Sometimes when I just don't know where to turn<br/>
In this life with miles to burn<br/>
Cities, the places that I have called home (my own)<br/>
Time to leave, time to be all on my own (I'm home)<br/>
<br/>
On my way now no need to pack<br/>
Just jump in that front seat and pull right back<br/>
On the little lever that holds me still<br/>
Then crank up the starter it's such a thrill<br/>
<br/>
To be driving, don't know where to<br/>
But I'm driving and so can you<br/>
I'm driving, to twist and twine<br/>
When I'm driving I feel fine<br/>
<br/>
Troubles, past those more than ten miles ago (no woes)<br/>
Fear and doubt can't catch me they move too slow (no)<br/>
Reasons, there's no need for me to explain (my brain)<br/>
Driving it helps me get rid of the pain (stay sane)<br/>
<br/>
Now it's time to pick up the pace<br/>
Put my foot down quickly it's like a race<br/>
To the furthest place from what I can see<br/>
And it helps me to clear out my memory<br/>
<br/>
To be driving this road I'm on<br/>
When I'm driving I'm not a pawn<br/>
Problems spewing out my exhaust<br/>
I've been driving so long now I'm lost<br/>
<br/>
Maybe I've gone just a little bit too far<br/>
It makes me wonder why we are<br/>
Running in circles but running from nothing<br/>
All of this rushing - so overwhelming<br/>
<br/>
Time to slow down now, life's meant to be savored<br/>
Not just zoom by cause that's unflavored<br/>
Familiar roads I can see in the distance<br/>
No more resistance<br/>
<br/>
It makes me twitchy<br/>
So exciting<br/>
For me<br/>
To be driving<br/>