So someone who you think is cool turns out to be your worst fear<br/>
Could be your boss or your girlfriend or your closest pal but it turns out they haven't been real<br/>
<br/>
They play all nice and act like your friend long enough to get you in their grasp<br/>
And just when you think that things are cool they rape you in your ass<br/>
<br/>
Fake people everywhere<br/>
What am I supposed to do?<br/>
Fake people everywhere<br/>
Watch out cause they're screwing you<br/>
Fake people everywhere<br/>
What am I supposed to say<br/>
Fake people everywhere<br/>
I wish that I could make them pay<br/>
<br/>
Fake people penetrate all of our society<br/>
Infecting the government and various powerful agencies<br/>
They hide in the ranks of corporations but you'll never know the place<br/>
Until they want to steal from you that's when they show their real face<br/>