First, there was a girl<br/>
And she was my heart<br/>
And she was my world<br/>
My friend I'd love to the end<br/>
<br/>
My only thought<br/>
Is that you were happy and true<br/>
And when you needed something<br/>
I was the one you'd look to<br/>
<br/>
And I died for you twice<br/>
I'd do it again<br/>
You were my life and my soul resides<br/>
In a world with no feeling<br/>
My words are revealing<br/>
I was a fool<br/>
I was a joke and this was a game<br/>
<br/>
And hell, I should be bitter<br/>
I should be mad - what does it matter?<br/>
I'll live and I'll die<br/>
You killed me again<br/>
<br/>
Love lasts like lullabies in time<br/>
The lives of our children are born on that rhyme<br/>
Trust me once for the good times we've had<br/>
Learn from the memories and don't feel that bad<br/>
<br/>
Know that I did it for you<br/>
I did it for love<br/>
For millions of men in their lifetime<br/>
Who would try for somebody else<br/>
Would cry for somebody else<br/>
Die for somebody else<br/>
<br/>
I have tried<br/>
I have cried<br/>
I have died<br/>
For you<br/>
