There's a love in the air today<br/>
And it makes me want to stay<br/>
But it makes me stay away<br/>
Cause I'm not over you<br/>
<br/>
And the little I can do<br/>
It won't be enough for you<br/>
Not with what I have today<br/>
But maybe someday soon<br/>
<br/>
You can't stop change<br/>
The world changes every day<br/>
I'm no exception<br/>
And I'm certainly not going away<br/>
<br/>
So I don't know to do<br/>
But I know that I love you<br/>
And I'll sit here in my room<br/>
'Til I get over you<br/>
<br/>
And there's plenty I could do<br/>
If I wanted to get you<br/>
I'm just not feeling that today<br/>
But maybe someday soon<br/>