There she is on the other side of my screen<br/>
I can reach out my hand, but I can't feel her face<br/>
I can only imagine how she would feel to me<br/>
My hand hits a wall of glass<br/>
<br/>
Internet Explorer Version 6.0<br/>
Just isn't enough to make me go<br/>
I am loved by the world, by a lovely girl<br/>
Computer, make me feel loved<br/>
<br/>
I can look but she won't respond to my feelings<br/>
I wanna reach out and grab her, pull her into my reality<br/>
I could die right here, her face as still as stone<br/>
My heart leaps out of my chest<br/>