Being overrun by the punk, by the pop<br/>
By the grunge rock potheads and the hip-hop thugs<br/>
A decade and a half of underground living<br/>
Carried on by the resolute few
<br/>
Metal is the sound that we've all come to know<br/>
It's the sound of our burning hearts<br/>
Some may say metal's seen better days<br/>
But here the new beginning starts<br/>
<br/>
Metal, you're not dead yet<br/>
No I say metal, you're not dead yet<br/>
<br/>
Angry sounds and angry words and over-frustrated tones
Therapeutic sonic sessions sawing through your bones
<br/>
The songs for the deaf and the underground left and the anthems of the insecure<br/>
Metal lives on in our souls and our hearts, of that you can be sure<br/>
<br/>
Metal, I breathe your life<br/>
You're all we got left<br/>
<br/>
Metal you have life as long as I say so, yeah<br/>