Es war einmal ein kleines Kind<br/>
Das einst mein Freund war<br/>
Es ist, so wie ich bevor ich<br/>
Aufgewachsen bin<br/>
<br/>
Es spricht zu meiner Dame und glaubt<br/>
Es hat eine Chance<br/>
Kann es nicht seinen Mund halten<br/>
Werd' ich's ihm schon beibringen<br/>
<br/>
Kannst du nicht sehen - und verstehen?<br/>
Ich spreche über - dich und nur dich<br/>
Deine Worte sind rau - ich denke nicht<br/>
Du kannst danach handeln - zu erbärmlich<br/>
<br/>
Du hast kranke Träume - denkst du denn wirklich<br/>
Sie gehört dir - und nicht mehr mir<br/>
Will ich es dir ganz - einfach erklären<br/>
So gut wie ich kann - hörst du mich nicht?<br/>
<br/>
Sie ist meine Frau - wenn sie nach mir fragt<br/>
Weißt du sie - wird dir nie gehören<br/>
Es ist an der Zeit - zu verstehen<br/>
Du bist nur mit ihr - im Traum zusammen<br/>
<br/>
Du denkst du bist schlau aber wenn du's bist<br/>
Würdest du sie nicht verfolgen <br/>
Du willst mit ihr schlafen, ich werd' dir dafür<br/>
Den ewigen Schlaf schenken<br/>
<br/>
Warum gehst du nicht?<br/>
Du wirst mich nicht mögen<br/>
Wenn ich hier bin<br/>
Ich hab dich gewarnt<br/>
<br/>
Du gehst mir unter die Haut<br/>
Du bist wie ein Geschwür<br/>
Das ich aus unserem<br/>
Dasein entfernen muss<br/>
<br/>
Doch sie ist mein Schatz - wenn sie mich begehrt<br/>
Weißt du sie - wird dir nie gehören<br/>
Du musst dir - selber eingestehen<br/>
Nur im Traum - wirst du sie sehen<br/>