Let's get fired up about politics!<br/>
Yeah, where are my republicans? My democrats?<br/>
We need everybody here in the house so we can have some chaos!<br/>
Yeah, that's what this country is about<br/>
Cause who wants to be an American idiot?<br/>
Oh, enough of that stupid song already<br/>
Fight, fight, fight, go!<br/>
Woo!<br/>
<br/>
We're the Republicans and we'd like say<br/>
That most of you are sinners and you hate us anyway<br/>
You hate us because we stand up for what's right<br/>
We wish that we could help but you insist that we fight<br/>
<br/>
Shut up!<br/>
I've had enough of your shit!<br/>
Politics, politics, politics<br/>
Six six six<br/>
Politics, politics six politics<br/>
Poli-six six six<br/>
Politics tics tics<br/>
<br/>
We're the Democrats and you can suck our dicks<br/>
Cause we won't take no fucking shit from you hypocrites<br/>
If you tell us one more lie we'll make a movie about you<br/>
And sing angry songs and talk trash about you<br/>
<br/>
Yeah, so do you understand me?<br/>
I don't care about this<br/>
I don't care about politics<br/>
Yeah, I just want to sit on my sofa<br/>
Read my magazine and watch the TV screen<br/>