I am System Of A Down and I like to criticize people<br/>
Without using my brain to consider any other point of view<br/>
I am so narrow minded, I open my mouth before I think<br/>
And I really can't believe that I really have my own CD<br/>
<br/>
I am smart and you are stupid<br/>
I am smart and you are dumb<br/>
<br/>
I was not aware that other people could have a different<br/>
Perspective on the world because I thought that everyone was just like me<br/>
I am so cool, I am so awesome, because I am in a band<br/>
And everybody worships me, I am so awesome, I love me<br/>
<br/>
Blastoff!<br/>