I wish you would put me to sleep I don't want to be here<br/>
There's no escape when I'm awake I don't want to be here<br/>
As far as I can tell there is no end to the pain<br/>
It never stops I've tried to stop I'm going insane<br/>
<br/>
I hate you<br/>
But I love you<br/>
<br/>
Take me away<br/>
<br/>
This is pointless I feel fine now I feel like crap<br/>
Because you don't treat me the way that you said you would<br/>
You stupid girl why don't you just tell me what you want<br/>
How am I supposed to know when you won't even communicate<br/>